services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: pizza_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - pizza_network

  streaming_service:
    build:
      context: .
      dockerfile: services/streaming/Dockerfile
    container_name: pizza_streaming
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./violation_frames:/app/violation_frames
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - pizza_network
    restart: unless-stopped

  detection_service:
    build:
      context: .
      dockerfile: services/detection/Dockerfile
    container_name: pizza_detection
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./violation_frames:/app/violation_frames
      - ./models:/app/models
      - ./services/detection/imgs:/app/detection/imgs:ro
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - pizza_network
    restart: unless-stopped
    command: ["python", "main.py", "--mode", "service","--model-path", "models/yolo12m-v2.pt", "--db-path", "data/violations.db", "--skip-frames", "30", "--output-path", "videos/output/output_video.mp4"]

  frame_reader:
    build:
      context: .
      dockerfile: services/frame_reader/Dockerfile
    container_name: pizza_frame_reader
    env_file:
      - .env
    volumes:
      - ./videos:/app/videos
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - pizza_network
    restart: unless-stopped
    command: ["python", "main.py", "--source", "/app/videos/Sah_w _b3dha_ghalt.mp4", "--fps", "30"]

  streamlit_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pizza_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - streaming_service
    networks:
      - pizza_network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  pizza_network:
    driver: bridge